BEGIN TRANSACTION;
SET CONSTRAINTS ALL DEFERRED;

DROP TABLE IF EXISTS users_fix CASCADE;
CREATE TABLE users_fix (
    id SERIAL PRIMARY KEY, 
    name TEXT,
    company TEXT,
    user_type TEXT
);

DROP TABLE IF EXISTS sessions_fix CASCADE;
CREATE TABLE sessions_fix (
    id SERIAL PRIMARY KEY,
    user_id INTEGER, -- REFERENCES users(id),
    session_type TEXT,
    CONSTRAINT owner FOREIGN KEY (user_id) REFERENCES users_fix(id) DEFERRABLE INITIALLY IMMEDIATE
);

DROP TABLE IF EXISTS queries_fix CASCADE;
CREATE TABLE queries_fix (
    id SERIAL PRIMARY KEY,
    text TEXT NOT NULL,
    time DOUBLE PRECISION,
    autogenerated BOOLEAN,
    searchtype TEXT,
    earliest_event DOUBLE PRECISION,
    latest_event DOUBLE PRECISION,
    range DOUBLE PRECISION,
    is_realtime BOOLEAN,
    splunk_search_id TEXT,
    runtime DOUBLE PRECISION,
    splunk_savedsearch_name TEXT,
    user_id INTEGER, -- REFERENCES users(id),
    session_id INTEGER, -- REFERENCES sessions(id),
    CONSTRAINT issuing_user FOREIGN KEY (user_id) REFERENCES users_fix(id) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT containing_session FOREIGN KEY (session_id) REFERENCES sessions_fix(id) DEFERRABLE INITIALLY IMMEDIATE
);

COMMIT;
